"""Foundation D — the shared multi-speaker ESCALATION SCENE fixture pack.

Three acted TTS scenes in ``server/tests/fixtures/audio/`` (generated by
``scripts/make_test_recording_scenes.py``), each with a designated "self"
speaker (always ``Speaker A``, always the SAME OpenAI voice), per-turn
scripted emotions + a coarse class, and a hand-authored expected-nudge
timeline. They exist so the watch-nudge, phone post-analysis and realtime
coaching tracks all test against ONE pack with known voices, known
emotions and a known nudge timeline.

Two kinds of test live here:

1. PURE (always run): every ``*_meta.json`` in the fixture dir is schema-
   consistent with its WAV — turn durations + gaps reproduce the file
   length, speakers/self/nudges/emotion_coarse are internally consistent,
   and the scene metas match the generator script's ``SCENES`` byte-for-
   byte (the same "script diffed against meta" ground-truth check the
   ladder report did by hand for the 2-speaker fixtures).

2. LIVE-GATED (torch + speechbrain present): ``diarize_local.diarize_turns``
   on each scene, scored with exact best-permutation per-turn accuracy and
   PINNED AT THE MEASURED VALUE — the ladder file's rule: if a pin regresses,
   investigate rather than lower the bar; if it improves, raise the pin.
   Plus a cross-scene voiceprint test: self enrolled from ONE scene must
   match self — and only self — in the other two.

MEASURED 2026-08-24 (current pipeline, pinned ECAPA revision, 16 kHz):

  couple_escalation  onyx + coral              num_speakers=2  13/13 = 1.000
  family3            onyx + ballad + nova      num_speakers=3  15/15 = 1.000
  meeting4           onyx + marin/ballad/nova  num_speakers=2  11/17 = 0.647
                     SELF isolated on all 6 of its turns; the three
                     colleagues merged into one cluster (k=3 rejected at
                     marginal cosine 0.339 vs STRONG_SEPARATION_COSINE 0.33 —
                     0.32 at the time; recalibrated 2026-08-27).

The meeting4 number is a REAL LIMIT, not a lazy pin. Four different 4-voice
sets were generated and measured before settling on this one:
  alloy/ballad/sage  -> k=3 (ballad+sage merged, 0.378 > 0.32), 15/19
  echo/ballad/nova   -> k=2 (echo pulled self in),              11/19
  cedar/ballad/nova  -> k=3 (cedar+SELF merged, 0.389 > 0.32),  12/17
  marin/ballad/nova  -> k=2 (colleagues merged; SELF isolated),  11/17  <- shipped
No 4-set of OpenAI TTS voices cleared the k=4 split bar; a scratch probe of
all 13 voices put the best possible worst-pair at ~0.30 single-utterance,
and real pooled centroids run 0.03-0.09 higher than that. The shipped set
is the one whose failure mode is LEAST harmful to the pack's purpose (self
attribution stays perfect, so nudge tests still work); the merged
colleagues are the documented ceiling. When the 4-voice pin here starts
failing UPWARD (num_speakers 3 or 4), that is the pipeline getting better —
re-measure and raise it.

Cross-scene self voiceprint (pooled Speaker A from one scene vs pooled
speakers of another): self 0.89-0.94, every non-self 0.09-0.28 — far either
side of ``speaker_id.MATCH_THRESHOLD`` (0.65).

The permutation-accuracy helper is a deliberate copy of the one in
``test_diarize_regression_ladder.py`` (test modules intentionally don't
import each other here).
"""

import itertools
import json
import wave
from pathlib import Path

import numpy as np
import pytest

import audio_ingest
import diarize_local
import speaker_id

_AUDIO_DIR = Path(__file__).resolve().parent / "fixtures" / "audio"

_SCENES = {
    "couple_escalation": _AUDIO_DIR / "test_recording_scene_couple_escalation.wav",
    "family3": _AUDIO_DIR / "test_recording_scene_family3.wav",
    "meeting4": _AUDIO_DIR / "test_recording_scene_meeting4.wav",
}

_COARSE = {"neutral", "angry", "sad", "happy"}
_LEVELS = {"mild", "strong"}


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------

def _meta_path(wav_path: Path) -> Path:
    return wav_path.with_name(wav_path.stem + "_meta.json")


def _wav_seconds(wav_path: Path) -> tuple[float, int]:
    with wave.open(str(wav_path), "rb") as wf:
        return wf.getnframes() / wf.getframerate(), wf.getframerate()


def _build_turns(meta: dict) -> list[dict]:
    """Same reconstruction as the ladder file: turns are concatenated
    back-to-back with a fixed ``silence_gap_sec`` between them, so
    (start, end) follows exactly from the per-turn ``duration_sec``."""
    gap = meta["silence_gap_sec"]
    turns, t = [], 0.0
    for m in meta["turns"]:
        turns.append({
            "speaker": m["speaker"],
            "text": m["text"],
            "start_time": round(t, 4),
            "end_time": round(t + m["duration_sec"], 4),
        })
        t += m["duration_sec"] + gap
    return turns


def _best_permutation_accuracy(
    truth: list[str], pred: list[str],
) -> tuple[float, int, dict[str, str]]:
    """Exact per-turn accuracy under the best bijection pred-label ->
    truth-label (copied from test_diarize_regression_ladder.py; see its
    docstring for why this beats pairwise Rand agreement here)."""
    truth_labels = sorted(set(truth))
    pred_labels = sorted(set(pred))
    best_acc, best_correct, best_map = -1.0, 0, {}
    width = min(len(truth_labels), len(pred_labels))
    for perm in itertools.permutations(truth_labels, width):
        mapping = dict(zip(pred_labels, perm))
        correct = sum(1 for t, p in zip(truth, pred) if mapping.get(p) == t)
        acc = correct / len(truth)
        if acc > best_acc:
            best_acc, best_correct, best_map = acc, correct, mapping
    return best_acc, best_correct, best_map


def _load_16k_pcm(wav_path: Path) -> tuple[np.ndarray, int]:
    """Production decode path (ffmpeg-backed, guaranteed 16 kHz). The scene
    fixtures are already 16 kHz so this is the stdlib fast path — but going
    through it keeps the contract identical to a real upload."""
    pcm, sr = audio_ingest.decode_to_pcm_16k(wav_path.read_bytes(), wav_path.name)
    assert sr == speaker_id.TARGET_SR
    return pcm, sr


# ---------------------------------------------------------------------------
# PURE: fixture schema consistency (every meta in the dir, not just scenes)
# ---------------------------------------------------------------------------

def _all_metas() -> list[Path]:
    return sorted(_AUDIO_DIR.glob("*_meta.json"))


@pytest.mark.parametrize("meta_path", _all_metas(), ids=lambda p: p.stem)
def test_fixture_meta_schema_consistent(meta_path: Path):
    """Every fixture meta must (a) describe turns, (b) agree with its WAV's
    sample rate and length, and (c) — where the richer scene fields are
    present — be internally consistent: speakers/self, expected_nudges,
    emotion_coarse. Legacy metas (physics, family_real, poker6) only get
    the checks their fields support; nothing is assumed."""
    meta = json.loads(meta_path.read_text())
    wav_path = meta_path.with_name(meta_path.name.replace("_meta.json", ".wav"))
    assert wav_path.exists(), f"{meta_path.name} has no WAV alongside it"
    file_sec, file_sr = _wav_seconds(wav_path)

    turns = meta.get("turns") or meta.get("approx_turns")
    assert turns, f"{meta_path.name}: no turns/approx_turns"
    assert all(isinstance(t.get("speaker"), str) and t["speaker"] for t in turns)

    if "sample_rate" in meta:
        assert meta["sample_rate"] == file_sr, (
            f"{meta_path.name}: meta sample_rate {meta['sample_rate']} != "
            f"WAV {file_sr}"
        )

    # Concatenated-TTS fixtures: durations + gaps must reproduce the file.
    if "silence_gap_sec" in meta and all("duration_sec" in t for t in turns):
        expected = (sum(t["duration_sec"] for t in turns)
                    + meta["silence_gap_sec"] * (len(turns) - 1))
        assert abs(expected - file_sec) < 0.01, (
            f"{meta_path.name}: sum(duration_sec)+gaps = {expected:.4f}s but "
            f"WAV is {file_sec:.4f}s"
        )

    # Timestamped fixtures: monotonic, inside the file.
    starts_ends = [
        (t.get("start_time", t.get("approx_start")), t.get("end_time", t.get("approx_end")))
        for t in turns
    ]
    if all(s is not None and e is not None for s, e in starts_ends):
        prev_end = 0.0
        for s, e in starts_ends:
            assert 0 <= s < e, f"{meta_path.name}: bad turn span {s}-{e}"
            assert s >= prev_end - 1e-6, f"{meta_path.name}: turns overlap at {s}"
            prev_end = e
        assert prev_end <= file_sec + 0.05, (
            f"{meta_path.name}: last turn ends at {prev_end}s, WAV is {file_sec:.2f}s"
        )

    # Scene-pack fields (present on the Foundation D fixtures).
    speakers = meta.get("speakers")
    if speakers is not None:
        assert set(t["speaker"] for t in turns) <= set(speakers), (
            f"{meta_path.name}: turn speaker not declared in `speakers`"
        )
        selfs = [k for k, v in speakers.items() if v.get("is_self")]
        assert len(selfs) == 1, f"{meta_path.name}: expected exactly one is_self, got {selfs}"
        assert meta.get("self_speaker") == selfs[0]
        assert meta.get("num_speakers_true") == len(speakers)
        assert all(v.get("voice") for v in speakers.values())

    if any("emotion_coarse" in t for t in turns):
        for i, t in enumerate(turns):
            assert t.get("emotion_coarse") in _COARSE, (
                f"{meta_path.name}: turn {i} emotion_coarse={t.get('emotion_coarse')!r}"
            )
            assert t.get("scripted_emotion"), f"{meta_path.name}: turn {i} lacks scripted_emotion"

    nudges = meta.get("expected_nudges")
    if nudges is not None:
        assert speakers is not None, f"{meta_path.name}: expected_nudges without speakers"
        self_label = meta["self_speaker"]
        seen = []
        for n in nudges:
            idx = n["after_turn_index"]
            assert isinstance(idx, int) and 0 <= idx < len(turns), (
                f"{meta_path.name}: nudge index {idx} out of range"
            )
            assert n["level"] in _LEVELS, f"{meta_path.name}: nudge level {n['level']!r}"
            assert isinstance(n.get("reason"), str) and n["reason"].strip()
            assert turns[idx]["speaker"] == self_label, (
                f"{meta_path.name}: nudge after turn {idx} but that turn is "
                f"{turns[idx]['speaker']}, not self ({self_label}) — a nudge on a "
                f"non-self turn is a false positive by construction"
            )
            seen.append(idx)
        assert seen == sorted(seen), f"{meta_path.name}: nudges must be in turn order"
        # The timeline is hand-authored, so keep it honest against the
        # script itself: every ANGRY self turn gets a nudge, nothing else does.
        angry_self = [
            i for i, t in enumerate(turns)
            if t["speaker"] == self_label and t.get("emotion_coarse") == "angry"
        ]
        assert seen == angry_self, (
            f"{meta_path.name}: expected_nudges {seen} != angry self turns {angry_self}"
        )


def test_scene_metas_match_generator_script():
    """The committed scene metas must be byte-for-byte what
    ``scripts/make_test_recording_scenes.py`` says they are (speaker, text,
    emotion, instruction, coarse class, voices, nudges) — i.e. the script IS
    the ground truth and the meta is its faithful record. Also pins the one
    cross-scene invariant the pack is built on: self is the same voice in
    every scene."""
    import make_test_recording_scenes as gen  # scripts/ is on pytest's pythonpath

    for name, wav_path in _SCENES.items():
        if not wav_path.exists():
            pytest.skip(f"{wav_path.name} missing — generate with "
                        "scripts/make_test_recording_scenes.py")
        meta = json.loads(_meta_path(wav_path).read_text())
        scene = gen.SCENES[name]
        assert meta["speakers"] == scene["speakers"], name
        assert meta["silence_gap_sec"] == scene["silence_gap_sec"], name
        assert meta["expected_nudges"] == scene["expected_nudges"], name
        assert len(meta["turns"]) == len(scene["turns"]), name
        for i, (m, s) in enumerate(zip(meta["turns"], scene["turns"])):
            for key in ("speaker", "text", "scripted_emotion", "instruction"):
                assert m[key] == s[key], f"{name} turn {i} {key}"
            assert m["emotion_coarse"] == gen.EMOTION_COARSE[s["scripted_emotion"]], (name, i)
        assert meta["speakers"][meta["self_speaker"]]["voice"] == gen.SELF_VOICE, name


# ---------------------------------------------------------------------------
# LIVE-GATED: diarize_local on each scene, pinned at the measured value
# ---------------------------------------------------------------------------

# Applied per-function (not as a module-level pytestmark) so the pure schema
# tests above always run, even without the voice deps.
_needs_voice_deps = pytest.mark.skipif(
    not speaker_id.is_available(),
    reason="voice deps (torch + speechbrain) not installed",
)
_needs_scene_fixtures = pytest.mark.skipif(
    not all(p.exists() for p in _SCENES.values()),
    reason=("scene fixtures missing — generate with "
            "scripts/make_test_recording_scenes.py"),
)


def _diarize_scene(name: str) -> tuple[dict, dict, list[str], list[str]]:
    wav_path = _SCENES[name]
    meta = json.loads(_meta_path(wav_path).read_text())
    pcm, sr = _load_16k_pcm(wav_path)
    turns = _build_turns(meta)
    truth = [t["speaker"] for t in turns]
    got = diarize_local.diarize_turns(pcm, sr, [dict(t) for t in turns])
    assert got is not None, f"{name}: local diarization returned nothing trustworthy"
    pred = [t["speaker"] for t in got["turns"]]
    assert len(pred) == len(truth), (
        f"{name}: predicted {len(pred)} turns, expected {len(truth)} "
        f"(word-level splitting fired unexpectedly: split_utterances="
        f"{got['split_utterances']})"
    )
    return meta, got, truth, pred


def _report(name: str, meta: dict, got: dict, truth: list[str], pred: list[str],
            mapping: dict[str, str], acc: float, correct: int) -> str:
    lines = [
        f"{name}: num_speakers={got['num_speakers']} (true "
        f"{meta['num_speakers_true']}), exact per-turn accuracy "
        f"{correct}/{len(truth)} = {acc:.4f}, pooled_cosine={got['pooled_cosine']:.3f}",
        "  k_evaluated: " + "; ".join(
            f"k={k['k']} ok={k['ok']}"
            + (f" marginal={k['marginal_pair_cosine']:.3f}" if "marginal_pair_cosine" in k else "")
            + (f" ({k['reason']})" if k.get("reason") else "")
            for k in got["k_evaluated"]
        ),
        "  turn  emotion           truth      pred        mapped     ok",
    ]
    for i, (t, p) in enumerate(zip(truth, pred)):
        lines.append(
            f"  {i:>4}  {meta['turns'][i]['scripted_emotion']:<16}  {t:<9}  "
            f"{p:<10}  {mapping.get(p, '???'):<9}  {mapping.get(p) == t}"
        )
    return "\n".join(lines)


def _score(name: str):
    meta, got, truth, pred = _diarize_scene(name)
    acc, correct, mapping = _best_permutation_accuracy(truth, pred)
    return meta, got, truth, pred, mapping, acc, correct


@_needs_voice_deps
@_needs_scene_fixtures
def test_scene_couple_escalation_pinned():
    """2 voices (onyx self + coral). Measured 2026-08-24: num_speakers=2,
    13/13 = 100% — including the shout_angry and cold_contempt self turns,
    which is the point (extreme acted register shifts must not spawn a
    phantom third voice, the failure the gptaudio fixture once showed)."""
    meta, got, truth, pred, mapping, acc, correct = _score("couple_escalation")
    msg = _report("couple_escalation", meta, got, truth, pred, mapping, acc, correct)
    assert got["num_speakers"] == 2, msg
    assert acc == 1.0, msg


@_needs_voice_deps
@_needs_scene_fixtures
def test_scene_family3_pinned():
    """3 voices (onyx self + ballad + nova), 0.25 s gaps (the rapid-turn
    case). Measured 2026-08-24: num_speakers=3, 15/15 = 100%; k=3 validated
    with marginal cosine 0.237 and anchor 0.065 — comfortably inside both
    bars, so this is the clean 3-speaker reference."""
    meta, got, truth, pred, mapping, acc, correct = _score("family3")
    msg = _report("family3", meta, got, truth, pred, mapping, acc, correct)
    assert got["num_speakers"] == 3, msg
    assert acc == 1.0, msg


@_needs_voice_deps
@_needs_scene_fixtures
def test_scene_meeting4_pinned():
    """4 voices (onyx self + marin/ballad/nova). Measured 2026-08-24:
    num_speakers=2, 11/17 = 0.647 — SELF isolated on all 6 of its turns, the
    three colleagues merged (k=3 rejected: marginal cosine 0.339 vs the
    STRONG_SEPARATION bar — 0.32 then, 0.33 since 2026-08-27, still under 0.339; k=4 never came close). See the module docstring
    for the four voice sets tried before accepting this as a real ceiling.

    Pinned EXACTLY at the measured value in both directions: a drop means a
    regression, a RISE means the pipeline now separates more of these
    voices — re-measure and raise the pin rather than leaving a stale floor.
    Self-isolation is asserted separately because that is the property the
    nudge tracks actually depend on."""
    meta, got, truth, pred, mapping, acc, correct = _score("meeting4")
    msg = _report("meeting4", meta, got, truth, pred, mapping, acc, correct)
    assert got["num_speakers"] == 2, msg
    assert correct == 11 and len(truth) == 17, msg

    # Self must be a cluster of its own: every self turn shares one predicted
    # label, and no non-self turn carries that label.
    self_label = meta["self_speaker"]
    self_preds = {p for t, p in zip(truth, pred) if t == self_label}
    other_preds = {p for t, p in zip(truth, pred) if t != self_label}
    assert len(self_preds) == 1 and not (self_preds & other_preds), msg


@_needs_voice_deps
@_needs_scene_fixtures
def test_self_voiceprint_transfers_across_scenes():
    """Enroll SELF from one scene (pool its Speaker A turns through the same
    ``speaker_id.pool_speaker_pcm`` + ``embed_pcm`` path voice enrollment
    uses) and check it against every pooled speaker in the other scenes:
    self must clear ``MATCH_THRESHOLD`` and be the best match; nobody else
    may clear it. Measured 2026-08-24: self 0.89-0.94, others 0.09-0.28,
    for every ordered scene pair. This is the invariant that lets the tracks
    enroll once and reuse the print across the whole pack."""
    pooled: dict[tuple[str, str], np.ndarray] = {}
    selfs: dict[str, str] = {}
    for name, wav_path in _SCENES.items():
        meta = json.loads(_meta_path(wav_path).read_text())
        pcm, sr = _load_16k_pcm(wav_path)
        turns = _build_turns(meta)
        selfs[name] = meta["self_speaker"]
        for spk in meta["speakers"]:
            pooled[(name, spk)] = speaker_id.embed_pcm(
                speaker_id.pool_speaker_pcm(pcm, sr, turns, spk), sr,
            )

    problems = []
    for a in _SCENES:
        enrolled = pooled[(a, selfs[a])]
        for b in _SCENES:
            if a == b:
                continue
            scores = {spk: speaker_id.cosine(enrolled, emb)
                      for (n, spk), emb in pooled.items() if n == b}
            best = max(scores, key=scores.get)
            if best != selfs[b] or scores[selfs[b]] < speaker_id.MATCH_THRESHOLD:
                problems.append(f"self@{a} vs {b}: self not the (thresholded) best: {scores}")
            for spk, c in scores.items():
                if spk != selfs[b] and c >= speaker_id.MATCH_THRESHOLD:
                    problems.append(f"self@{a} vs {b}: non-self {spk} matched at {c:.3f}")
    assert not problems, "\n".join(problems)



# ---------------------------------------------------------------------------
# Windows-first engine counterparts (2026-08-30; production's default engine —
# see test_diarize_regression_ladder.py's windows-first section for the
# per-utterance scoring rule, copied here).
# ---------------------------------------------------------------------------

def _windows_first_utterance_labels(turns: list[dict], got: dict) -> list[str]:
    out = []
    for t in turns:
        s, e = float(t["start_time"]), float(t["end_time"])
        weight: dict[str, float] = {}
        for o in got["turns"]:
            if o["text"] == diarize_local.UNTRANSCRIBED_TEXT:
                continue
            mid = (float(o["start_time"]) + float(o["end_time"])) / 2
            if s <= mid <= e:
                weight[o["speaker"]] = weight.get(o["speaker"], 0.0) + (
                    float(o["end_time"]) - float(o["start_time"])
                )
        out.append(max(weight, key=weight.get) if weight else "???")
    return out


def _score_windows(name: str):
    wav_path = _SCENES[name]
    meta = json.loads(_meta_path(wav_path).read_text())
    pcm, sr = _load_16k_pcm(wav_path)
    turns = _build_turns(meta)
    truth = [t["speaker"] for t in turns]
    got = diarize_local.diarize_windows_first(pcm, sr, [dict(t) for t in turns])
    assert got is not None, f"{name}: the windows engine returned nothing"
    pred = _windows_first_utterance_labels(turns, got)
    acc, correct, mapping = _best_permutation_accuracy(truth, pred)
    lines = [
        f"{name} (windows engine): num_speakers={got['num_speakers']} (true "
        f"{meta['num_speakers_true']}), {correct}/{len(truth)} = {acc:.4f}, "
        f"eigengap k={got['k_evaluated'][0]['k_eigengap']} (eigenvalues "
        f"{got['k_evaluated'][0]['eigenvalues']}), pooled_cosine={got['pooled_cosine']:.3f}, "
        f"{len(got['turns'])} turn(s), {got['split_utterances']} split",
        "  turn  emotion           truth      pred        mapped     ok",
    ]
    for i, (t, p) in enumerate(zip(truth, pred)):
        lines.append(
            f"  {i:>4}  {meta['turns'][i]['scripted_emotion']:<16}  {t:<9}  "
            f"{p:<10}  {mapping.get(p, '???'):<9}  {mapping.get(p) == t}"
        )
    return meta, got, truth, pred, acc, correct, "\n".join(lines)


@_needs_voice_deps
@_needs_scene_fixtures
def test_windows_first_scene_couple_escalation_pinned():
    """Measured 2026-08-30: eigengap k=2, 13/13 (frame accuracy 1.000)."""
    meta, got, truth, pred, acc, correct, msg = _score_windows("couple_escalation")
    assert got["num_speakers"] == 2, msg
    assert acc == 1.0, msg


@_needs_voice_deps
@_needs_scene_fixtures
def test_windows_first_scene_family3_pinned():
    """Measured 2026-08-30: eigengap k=3, 15/15 (frame accuracy 1.000)."""
    meta, got, truth, pred, acc, correct, msg = _score_windows("family3")
    assert got["num_speakers"] == 3, msg
    assert acc == 1.0, msg


@_needs_voice_deps
@_needs_scene_fixtures
def test_windows_first_scene_meeting4_pinned():
    """4 voices. Measured 2026-08-30: eigengap k=3 (D absorbed into B, the
    bake-off's documented ceiling — pooled B/D cosine 0.72), frame accuracy
    0.818 vs the utterance engine's 0.597 (k=2): self isolated, two of the
    three colleagues separated. Pinned EXACTLY (both directions) like the
    utterance-engine pin above; a rise to k=4 is the pipeline improving —
    re-measure and raise."""
    meta, got, truth, pred, acc, correct, msg = _score_windows("meeting4")
    assert got["num_speakers"] == 3, msg
    assert correct == 14 and len(truth) == 17, msg
    self_label = meta["self_speaker"]
    self_preds = {p for t, p in zip(truth, pred) if t == self_label}
    other_preds = {p for t, p in zip(truth, pred) if t != self_label}
    assert len(self_preds) == 1 and not (self_preds & other_preds), msg
